export enum AuditAction {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  PROFILE_UPDATE = "PROFILE_UPDATE",
  PASSWORD_CHANGE = "PASSWORD_CHANGE",
  ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED",
  ACCOUNT_REACTIVATED = "ACCOUNT_REACTIVATED"
}
